from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING, Any


# ============================================================
# TYPE-CHECKING IMPORTS
# ============================================================
#
# IMPORTANT:
#
# GNNRiskInference is only needed for type annotations here.
# Importing it at runtime creates this circular dependency:
#
#     gnn_inference
#          ↓
#     gnn_risk_governor
#          ↓
#     gnn_governor_integration
#          ↓
#     gnn_inference
#
# Therefore it must NOT be imported at runtime.
#
# `from __future__ import annotations` allows us to safely
# reference GNNRiskInference in annotations without importing
# it during module initialization.
# ============================================================

if TYPE_CHECKING:

    from .gnn_inference import GNNRiskInference


# ============================================================
# GOVERNOR ACTIONS
# ============================================================


class GovernorAction(str, Enum):

    ALLOW_AGENT_A_DECISION = (
        "ALLOW_AGENT_A_DECISION"
    )

    REQUEST_ADDITIONAL_EVIDENCE = (
        "REQUEST_ADDITIONAL_EVIDENCE"
    )

    ESCALATE_TO_HUMAN_REVIEW = (
        "ESCALATE_TO_HUMAN_REVIEW"
    )


# ============================================================
# GNN OBSERVATION
# ============================================================


@dataclass(frozen=True)
class GNNObservation:
    """
    Observation generated by the GNN layer.

    The GNN produces one external signal:

        gnn_risk

    It does not make the final Governor decision.
    """

    customer_id: str

    customer_node_index: int

    gnn_risk: float


# ============================================================
# GOVERNOR OBSERVATION
# ============================================================


@dataclass(frozen=True)
class GovernorObservation:
    """
    Unified observation passed between the GNN adapter
    and the higher-level Governor/Fusion layers.

    These are external observability signals.

    Agent A does NOT receive these fields.
    """

    customer_id: str

    # --------------------------------------------------------
    # GNN signal
    # --------------------------------------------------------

    gnn_risk: float

    # --------------------------------------------------------
    # Existing Governor signal
    # --------------------------------------------------------

    governor_risk: float

    # --------------------------------------------------------
    # Network / temporal signals
    # --------------------------------------------------------

    network_risk: float

    temporal_abnormality: float

    # --------------------------------------------------------
    # Semantic signals
    # --------------------------------------------------------

    semantic_paraphrase_score: float

    semantic_claim_switch: float

    evidence_consistency: float

    claim_similarity: float

    # --------------------------------------------------------
    # Behavioral / velocity signals
    # --------------------------------------------------------

    request_velocity: float

    amount_acceleration: float

    # --------------------------------------------------------
    # Shared infrastructure signals
    # --------------------------------------------------------

    shared_identifier_strength: float

    # --------------------------------------------------------
    # Agent-side observability
    # --------------------------------------------------------

    agent_decision_anomaly: float

    # --------------------------------------------------------
    # Strategic behavior
    # --------------------------------------------------------

    strategic_behavior: float


# ============================================================
# GNN → GOVERNOR ADAPTER
# ============================================================


class GNNGovernorAdapter:
    """
    Connects the trained GNN risk model to the
    Adaptive Risk Governor.

    The GNN provides ONE additional risk signal:

        gnn_risk

    It does not independently make the final
    Governor decision.

    Important architectural boundary:

        Agent A
            ↓
        produces support decision

        Governor
            ↓
        observes external signals

        GNN
            ↓
        produces gnn_risk

        Fusion
            ↓
        produces final risk decision


    Agent A does NOT receive:

        - gnn_risk
        - network risk
        - strategic adaptation score
        - fused risk
        - Governor reason codes
    """

    def __init__(
        self,
        gnn_inference: GNNRiskInference | None = None,
    ) -> None:

        # ----------------------------------------------------
        # Import lazily when no inference object is supplied.
        #
        # This provides an additional layer of protection
        # against circular imports.
        # ----------------------------------------------------

        if gnn_inference is None:

            from .gnn_inference import (
                GNNRiskInference,
            )

            gnn_inference = GNNRiskInference()

        self.gnn = gnn_inference

    # ========================================================
    # GENERATE GNN OBSERVATION
    # ========================================================

    def observe_customer(
        self,
        data: Any,
        customer_id: str,
        customer_node_index: int,
    ) -> GNNObservation:
        """
        Generate the GNN risk score for one customer.

        Parameters
        ----------
        data:
            PyTorch Geometric graph.

        customer_id:
            External customer identifier.

        customer_node_index:
            Customer node index inside the graph.
        """

        # ----------------------------------------------------
        # Validate customer node index
        # ----------------------------------------------------

        if customer_node_index < 0:

            raise ValueError(
                "Customer node index cannot be negative."
            )

        if customer_node_index >= data.num_nodes:

            raise ValueError(
                "Customer node index is outside the graph."
            )

        # ----------------------------------------------------
        # Run GNN inference
        # ----------------------------------------------------

        risk = self.gnn.predict_customer_risk(
            data=data,
            customer_node_index=customer_node_index,
        )

        risk = self._bounded(risk)

        # ----------------------------------------------------
        # Return immutable observation
        # ----------------------------------------------------

        return GNNObservation(
            customer_id=customer_id,
            customer_node_index=customer_node_index,
            gnn_risk=risk,
        )

    # ========================================================
    # AUGMENT GOVERNOR OBSERVATION
    # ========================================================

    def augment_observation(
        self,
        observation: Any,
        data: Any,
        customer_id: str,
        customer_node_index: int,
    ) -> GovernorObservation:
        """
        Add the GNN signal to an existing Governor result.

        The current AdaptiveRiskGovernor returns:

            GovernorDecision(
                risk_score=...,
                features={...},
                ...
            )

        Therefore the Governor risk is extracted from:

            observation.risk_score

        and NOT:

            observation.governor_risk

        The latter belongs to GovernorObservation.

        This method therefore acts as an explicit adapter
        between the two representations.
        """

        # ----------------------------------------------------
        # Generate GNN observation
        # ----------------------------------------------------

        gnn_observation = self.observe_customer(
            data=data,
            customer_id=customer_id,
            customer_node_index=customer_node_index,
        )

        # ----------------------------------------------------
        # Extract Governor feature dictionary
        # ----------------------------------------------------

        features = getattr(
            observation,
            "features",
            {},
        )

        if not isinstance(features, dict):

            features = {}

        # ====================================================
        # GOVERNOR RISK
        # ====================================================

        governor_risk = self._extract_float(
            observation,
            "risk_score",
            default=0.0,
        )

        # ====================================================
        # NETWORK RISK
        # ====================================================

        network_risk = self._extract_feature(
            features,
            "network_risk",
            default=0.0,
        )

        # ====================================================
        # TEMPORAL ABNORMALITY
        # ====================================================

        temporal_abnormality = self._extract_feature(
            features,
            "temporal_abnormality",
            default=0.0,
        )

        # ====================================================
        # SEMANTIC PARAPHRASE
        # ====================================================

        semantic_paraphrase_score = self._extract_feature(
            features,
            "semantic_paraphrase_score",
            default=0.0,
        )

        # ====================================================
        # SEMANTIC CLAIM SWITCH
        # ====================================================

        semantic_claim_switch = self._extract_feature(
            features,
            "semantic_claim_switch",
            default=0.0,
        )

        # ====================================================
        # EVIDENCE CONSISTENCY
        # ====================================================

        evidence_consistency = self._extract_feature(
            features,
            "evidence_consistency",
            default=0.0,
        )

        # ====================================================
        # CLAIM SIMILARITY
        # ====================================================

        claim_similarity = self._extract_feature(
            features,
            "claim_similarity",
            default=0.0,
        )

        # ====================================================
        # REQUEST VELOCITY
        # ====================================================

        request_velocity = self._extract_feature(
            features,
            "request_velocity",
            default=0.0,
        )

        # ====================================================
        # AMOUNT ACCELERATION
        # ====================================================

        amount_acceleration = self._extract_feature(
            features,
            "amount_acceleration",
            default=0.0,
        )

        # ====================================================
        # SHARED IDENTIFIER STRENGTH
        # ====================================================

        shared_identifier_strength = (
            self._extract_feature(
                features,
                "shared_identifier_strength",
                default=0.0,
            )
        )

        # ====================================================
        # AGENT DECISION ANOMALY
        # ====================================================

        agent_decision_anomaly = (
            self._extract_feature(
                features,
                "agent_decision_anomaly",
                default=0.0,
            )
        )

        # ====================================================
        # STRATEGIC BEHAVIOR
        # ====================================================
        #
        # Existing Governor terminology:
        #
        #     strategic_adaptation_score
        #
        # Unified observation terminology:
        #
        #     strategic_behavior
        #
        # ====================================================

        strategic_behavior = self._extract_feature(
            features,
            "strategic_adaptation_score",
            default=0.0,
        )

        # ====================================================
        # BUILD UNIFIED OBSERVATION
        # ====================================================

        return GovernorObservation(

            customer_id=customer_id,

            gnn_risk=(
                gnn_observation.gnn_risk
            ),

            governor_risk=(
                governor_risk
            ),

            network_risk=(
                network_risk
            ),

            temporal_abnormality=(
                temporal_abnormality
            ),

            semantic_paraphrase_score=(
                semantic_paraphrase_score
            ),

            semantic_claim_switch=(
                semantic_claim_switch
            ),

            evidence_consistency=(
                evidence_consistency
            ),

            claim_similarity=(
                claim_similarity
            ),

            request_velocity=(
                request_velocity
            ),

            amount_acceleration=(
                amount_acceleration
            ),

            shared_identifier_strength=(
                shared_identifier_strength
            ),

            agent_decision_anomaly=(
                agent_decision_anomaly
            ),

            strategic_behavior=(
                strategic_behavior
            ),
        )

    # ========================================================
    # NUMERIC ATTRIBUTE EXTRACTION
    # ========================================================

    @staticmethod
    def _extract_float(
        obj: Any,
        attribute: str,
        default: float = 0.0,
    ) -> float:
        """
        Safely extract a numeric attribute from an object.
        """

        try:

            value = getattr(
                obj,
                attribute,
                default,
            )

            return GNNGovernorAdapter._bounded(
                float(value)
            )

        except (
            TypeError,
            ValueError,
        ):

            return default

    # ========================================================
    # FEATURE DICTIONARY EXTRACTION
    # ========================================================

    @staticmethod
    def _extract_feature(
        features: dict[str, Any],
        name: str,
        default: float = 0.0,
    ) -> float:
        """
        Safely extract a numeric feature from a dictionary.
        """

        try:

            value = features.get(
                name,
                default,
            )

            return GNNGovernorAdapter._bounded(
                float(value)
            )

        except (
            TypeError,
            ValueError,
        ):

            return default

    # ========================================================
    # BOUND VALUE
    # ========================================================

    @staticmethod
    def _bounded(
        value: float,
    ) -> float:
        """
        Clamp a risk/feature value into [0, 1].
        """

        try:

            value = float(value)

        except (
            TypeError,
            ValueError,
        ):

            return 0.0

        return max(
            0.0,
            min(
                value,
                1.0,
            ),
        )


# ============================================================
# MODULE SELF-CHECK
# ============================================================

if __name__ == "__main__":

    print("=" * 70)
    print("GNN GOVERNOR INTEGRATION")
    print("=" * 70)

    print(
        "GNNGovernorAdapter definition loaded."
    )

    print(
        "Runtime circular-import protection: ENABLED"
    )

    print(
        "GNNRiskInference imported only when required."
    )

    print("=" * 70)
    print("SELF-CHECK PASSED")
    print("=" * 70)